### ISSUE TITLE
Desktop GUI

### ISSUE THREAD

**Issue by pavlo-v-chernykh** [pillserg/golr#11]
Hi, I remember you wanted to create desktop GUI for golr. I also want to play with some GUI stuff in Rust. It would be nice to try several GUI lib.  Which one would you like to use? Just curious, don't want to overlap. I see next variants on the horizon: qml and piston. I would like to go with qml.

**Comment by pillserg** [comment]
Ive thought about piston so no overlaping )

**Comment by pavlo-v-chernykh** [comment]
Great, I will go with qml. Needs more investigations according to code organisation with several entry points, etc. I think it is possible in cargo project. I'll do it later.

**Comment by pillserg** [comment]
surprizingly piston compiles and runs )
Do you think we can get past deps hell with usage of "cfg" (something like this on draw func http://www.reddit.com/r/rust/comments/2nlyhl/conditional_compilation/) or some compilation flags on cargo level are needed?

**Comment by pavlo-v-chernykh** [comment]
Going to try https://github.com/cyndis/qmlrs on weekend

**Comment by pavlo-v-chernykh** [comment]
Unfortunately could not build qmlrs (((. 
Not ready to put more efforts to it now. 
Close it.
