### ISSUE TITLE
Provide project license

### ISSUE THREAD

**Issue by pavlo-v-chernykh** [pillserg/golr#2]
I would like to add license file for the project. [Which one](http://choosealicense.com/) your prefer? My choice is MIT.

**Comment by pillserg** [comment]
Mit is cool

**Comment by pavlo-v-chernykh** [comment]
Can I consider it as approval?

**Comment by pillserg** [comment]
yep

**Comment by pillserg** [comment]
Looks like you are using me as training material... i don't feel love in this messages :)

**Comment by pavlo-v-chernykh** [comment]
:smile_cat: closed by 9ec5161ae457f7b1f7587670c8f8c9fde99f89e6
