### ISSUE TITLE
Replace custom Drawable with Display trait

### ISSUE THREAD

**Issue by pavlo-v-chernykh** [pillserg/golr#6]
I propose to replace Drawable with [fmt::Display](http://doc.rust-lang.org/std/fmt/trait.Display.html). What do you think about it?

**Comment by pillserg** [comment]
Feel free :)
Just don't remove display mod - i'm planning on trying piston there

**Comment by pavlo-v-chernykh** [comment]
Ok. I'll try to do it in recent days.

**Comment by pavlo-v-chernykh** [comment]
:smile_cat: closed by e41c4213a38caf71e0591efb3707c76d354cc386
